name: Docker Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV

      - name: Build and tag Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          load: false
          target: base
          build-args: |
            BASE_IMAGE=nvidia/cuda:12.6.3-runtime-ubuntu22.04
            VERSION=v0.3.9
          tags: |
            jamesbrink/comfyui:latest
            jamesbrink/comfyui:${{ github.sha }}
            jamesbrink/comfyui:${{ env.BRANCH_NAME }}
            jamesbrink/comfyui:v0.3.9
